language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo test --no-fail-fast -- --nocapture
