[package]
name = "rustfm-scrobble"
version = "0.1.1"
authors = ["David Futcher <bobbo@ubuntu.com>"]
description = "Last.fm Scrobble library for Rust"
repository = "https://github.com/bobbo/rustfm-scrobble"
keywords = ["last-fm", "scrobble", "api"]
license = "MIT"
readme = "README.md"
categories = ["api-bindings", "multimedia"]

[dependencies]
hyper = "0.10.4"
hyper-native-tls = "0.2.2"
rust-crypto = "0.2.36"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
